#list of GitHub organization usernames, grouped by type
organizations:

  United States:
    - adlnet
    - cfpb
    - chaos
    - cmsgov
    - commercegov
    - department-of-veterans-affairs
    - educationdatainitiative
    - erdc-cm
    - fcc
    - gsa
    - gsa-ocsit
    - hhs
    - historyatstate
    - hpc
    - imls
    - informaticslab
    - libraryofcongress
    - losalamos
    - mcc-gov
    - nasa
    - nationalparkservice
    - ncbitools
    - ncip
    - nhlbi
    - nrel
    - opengovplatform
    - ozoneplatform
    - peacecorps
    - presidential-innovation-fellows
    - redhawksdr
    - usagov
    - usaid
    - usasearch
    - usda
    - usdepartmentoflabor
    - usepa
    - usgs
    - usnationalarchives
    - whitehouse
#   - USDA-ERS
#   - usinterior

  Australia:
    - actgov

  Argentina:
    - gcba

  Brazil:
    - interlegis
    - gabinetedigital
    - plonegovbr
    - dadosgovbr

  Canada:
    - cityofgreatersudbury
    - cityofottawa
    - nsgov
    - pwgsc
    - wet-boew

  European Union:
    - europeana

  Finland:
    - avoinministerio
    - City-of-Helsinki

  France:
    - etalab

  Norway:
    - difi

  Sweden:
    - libris
    - rinfo
    - edelegationen
    - The-Municipality-of-Staffanstorp

  Puerto Rico:
    - commonwealth-of-puerto-rico

  United Kingdom:
    - alphagov
    - ministryofjustice
    - lichfield-district-council
    - east-sussex-county-council

  Estonia:
    - vvk-ehk

  International:
    - ogpl

  U.S. States:
    - agrc
    - nysenate
#    - wsdot
    - nys-its

  U.S. County:
    - sfcta
    - miamidade
    - slugis

  U.S. Special District:
    - cleveland-metroparks

  U.S. City:
    - chicago
#    - sfgov
    - cityofnewyork
    - octolabs
    - city-of-bloomington
    - city-of-bellingham
    - egovpdx
    - NYCComptroller
    - CityOfPhiladelphia
    - cambridgegis
    - cocdata
    - CityOfBoston
    - openlexington
    - CORaleigh

  Civic Hackers:
    - codeforamerica
    - sunlightlabs
    - opengovfoundation
    - open-city
    - gitmachines
    - dobtco
    - openplans
    - okfde
    - okfn
    - openoakland
    - localdata
    - unitedstates
    - statedecoded
    - openva
    - localwiki
    - civio
    - bundestag
    - teampopong
    - mysociety
    - openaustralia
    - okfn-brasil
    - dataviz
    - OpenTwinCities
    - thacker
    - opennorth
    - hasadna

#global settings
title: "Make government better, together."
description: "Stories of open data, open source, and open collaboration"
permalink: "/stories/:title"
url: http://government.github.com
relative_permalinks: false
prose_server: "http://prose.io"
tagline: 'Stories of <a href="/categories/#open-source"class="open source" title="Code or creation materials made easily accessible and free to the public.">open source</a>, <a href="/categories/#open-data" class="open data" title="Data made easily accessible and fee to the public.">open data</a>, and <a href="/categories/#open-government" class="open government" title="An acessible, transparent and forthcoming with data government agency.">open government</a>.'
analytics_account: "UA-3769691-28"

#build settings
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "node_modules"]
root: "/"
paginate: 6
markdown: kramdown
