name: Test site build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 1.0
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 1.7x
    - name: Build and test site
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
