name: Ensure entries are alphabetized

on:
  push:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"
  pull_request:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Ensure Orgs are sorted
      run: |
        bundle exec script/alphabetize
        git diff --color
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "Mike Linksvayer"
        author_email: "mlinksva@github.com"
        message: 'Autosort'
        add: '_data'
