name: Ensure entries are alphabetized

on:
  push:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"
  pull_request:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Ensure Orgs are sorted
      run: |
        bundle exec script/alphabetize
        git diff --color
    - uses: getsentry/action-git-diff-suggestions@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: ensure-alphabetize
